### ISSUE TITLE
Make this part of demo shorter

### ISSUE THREAD

**Issue by georg-nuehrenberg** [dependable-ai/nn-dependability-kit#6]
Maybe we can stop after 3 steps.
![grafik](https://user-images.githubusercontent.com/6159245/48195390-d3322300-e34f-11e8-9f21-a98c1c3d00fb.png)

**Comment by chengchihhong** [comment]
Yes that's good. I always manually stop and trigger exception.

**Comment by georg-nuehrenberg** [comment]
I'll do the same for MNIST_Neuron2ProjectionCoverage_TestGen

**Comment by georg-nuehrenberg** [comment]
Done
