### ISSUE TITLE
Handle the case when no testcase for the pattern can be generated

### ISSUE THREAD

**Issue by georg-nuehrenberg** [dependable-ai/nn-dependability-kit#7]
Two options: try another image, or select a fixed image for which it works?
![grafik](https://user-images.githubusercontent.com/6159245/48195707-ab8f8a80-e350-11e8-9958-c60e66074cbf.png)

**Comment by georg-nuehrenberg** [comment]
ok, here also MNIST_Neuron2ProjectionCoverage_TestGen

**Comment by chengchihhong** [comment]
Finished.
